/*
 * Ziti Edge Client
 * OpenZiti Edge Client API
 *
 * The version of the OpenAPI document: 0.26.18
 * Contact: help@openziti.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openziti.edge.model;

import org.junit.jupiter.api.Test;

/** Model tests for BaseEntity */
class BaseEntityTest {
    private final BaseEntity model = new BaseEntity();

    /** Model tests for BaseEntity */
    @Test
    void testBaseEntity() {
        // TODO: test BaseEntity
    }

    /** Test the property 'links' */
    @Test
    void linksTest() {
        // TODO: test links
    }

    /** Test the property 'createdAt' */
    @Test
    void createdAtTest() {
        // TODO: test createdAt
    }

    /** Test the property 'id' */
    @Test
    void idTest() {
        // TODO: test id
    }

    /** Test the property 'tags' */
    @Test
    void tagsTest() {
        // TODO: test tags
    }

    /** Test the property 'updatedAt' */
    @Test
    void updatedAtTest() {
        // TODO: test updatedAt
    }
}
