/*
 * Ziti Edge Management
 * OpenZiti Edge Management API
 *
 * The version of the OpenAPI document: 0.31.0
 * Contact: help@openziti.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openziti.management.api;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.time.Duration;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.StringJoiner;
import java.util.concurrent.CompletableFuture;
import java.util.function.Consumer;
import org.openziti.management.ApiClient;
import org.openziti.management.ApiException;
import org.openziti.management.ApiResponse;
import org.openziti.management.Configuration;
import org.openziti.management.Pair;
import org.openziti.management.model.ControllerSettingCreate;
import org.openziti.management.model.ControllerSettingPatch;
import org.openziti.management.model.ControllerSettingUpdate;
import org.openziti.management.model.CreateEnvelope;
import org.openziti.management.model.DetailControllerSettingEffectiveEnvelope;
import org.openziti.management.model.DetailControllerSettingEnvelope;
import org.openziti.management.model.Empty;
import org.openziti.management.model.ListControllerSettingEnvelope;

@javax.annotation.Generated(
        value = "org.openapitools.codegen.languages.JavaClientCodegen",
        date = "2026-06-04T09:00:03.854034-04:00[America/New_York]",
        comments = "Generator version: 7.22.0")
public class SettingsApi {
    /** Utility class for extending HttpRequest.Builder functionality. */
    private static class HttpRequestBuilderExtensions {
        /**
         * Adds additional headers to the provided HttpRequest.Builder. Useful for adding
         * method/endpoint specific headers.
         *
         * @param builder the HttpRequest.Builder to which headers will be added
         * @param headers a map of header names and values to add; may be null
         * @return the same HttpRequest.Builder instance with the additional headers set
         */
        static HttpRequest.Builder withAdditionalHeaders(
                HttpRequest.Builder builder, Map<String, String> headers) {
            if (headers != null) {
                for (Map.Entry<String, String> entry : headers.entrySet()) {
                    builder.header(entry.getKey(), entry.getValue());
                }
            }
            return builder;
        }
    }

    private final HttpClient memberVarHttpClient;
    private final ObjectMapper memberVarObjectMapper;
    private final String memberVarBaseUri;
    private final Consumer<HttpRequest.Builder> memberVarInterceptor;
    private final Duration memberVarReadTimeout;
    private final Consumer<HttpResponse<InputStream>> memberVarResponseInterceptor;
    private final Consumer<HttpResponse<InputStream>> memberVarAsyncResponseInterceptor;

    public SettingsApi() {
        this(Configuration.getDefaultApiClient());
    }

    public SettingsApi(ApiClient apiClient) {
        memberVarHttpClient = apiClient.getHttpClient();
        memberVarObjectMapper = apiClient.getObjectMapper();
        memberVarBaseUri = apiClient.getBaseUri();
        memberVarInterceptor = apiClient.getRequestInterceptor();
        memberVarReadTimeout = apiClient.getReadTimeout();
        memberVarResponseInterceptor = apiClient.getResponseInterceptor();
        memberVarAsyncResponseInterceptor = apiClient.getAsyncResponseInterceptor();
    }

    private ApiException getApiException(String operationId, HttpResponse<InputStream> response) {
        try {
            InputStream responseBody = ApiClient.getResponseBody(response);
            String body = null;
            if (responseBody != null) {
                body = new String(responseBody.readAllBytes());
                responseBody.close();
            }
            String message = formatExceptionMessage(operationId, response.statusCode(), body);
            return new ApiException(response.statusCode(), message, response.headers(), body);
        } catch (IOException e) {
            return new ApiException(e);
        }
    }

    private String formatExceptionMessage(String operationId, int statusCode, String body) {
        if (body == null || body.isEmpty()) {
            body = "[no body]";
        }
        return operationId + " call failed with: " + statusCode + " - " + body;
    }

    /**
     * Download file from the given response.
     *
     * @param response Response
     * @return File
     * @throws ApiException If fail to read file content from response and write to disk
     */
    public File downloadFileFromResponse(
            HttpResponse<InputStream> response, InputStream responseBody) throws ApiException {
        if (responseBody == null) {
            throw new ApiException(new IOException("Response body is empty"));
        }
        try {
            File file = prepareDownloadFile(response);
            java.nio.file.Files.copy(
                    responseBody, file.toPath(), java.nio.file.StandardCopyOption.REPLACE_EXISTING);
            return file;
        } catch (IOException e) {
            throw new ApiException(e);
        }
    }

    /**
     * Prepare the file for download from the response.
     *
     * @param response a {@link java.net.http.HttpResponse} object.
     * @return a {@link java.io.File} object.
     * @throws java.io.IOException if any.
     */
    private File prepareDownloadFile(HttpResponse<InputStream> response) throws IOException {
        String filename = null;
        java.util.Optional<String> contentDisposition =
                response.headers().firstValue("Content-Disposition");
        if (contentDisposition.isPresent() && !"".equals(contentDisposition.get())) {
            // Get filename from the Content-Disposition header.
            java.util.regex.Pattern pattern =
                    java.util.regex.Pattern.compile("filename=['\"]?([^'\"\\s]+)['\"]?");
            java.util.regex.Matcher matcher = pattern.matcher(contentDisposition.get());
            if (matcher.find()) filename = matcher.group(1);
        }
        File file = null;
        if (filename != null) {
            java.nio.file.Path tempDir =
                    java.nio.file.Files.createTempDirectory("swagger-gen-native");
            java.nio.file.Path filePath = java.nio.file.Files.createFile(tempDir.resolve(filename));
            file = filePath.toFile();
            tempDir.toFile().deleteOnExit(); // best effort cleanup
            file.deleteOnExit(); // best effort cleanup
        } else {
            file = java.nio.file.Files.createTempFile("download-", "").toFile();
            file.deleteOnExit(); // best effort cleanup
        }
        return file;
    }

    /**
     * Create a controller specific setting Create a new controller specific settings object.
     * Requires admin access.
     *
     * @param controllerSetting A controller settings object to create (required)
     * @return CompletableFuture&lt;CreateEnvelope&gt;
     * @throws ApiException if fails to make API call
     */
    public CompletableFuture<CreateEnvelope> createControllerSetting(
            @javax.annotation.Nonnull ControllerSettingCreate controllerSetting)
            throws ApiException {
        return createControllerSetting(controllerSetting, null);
    }

    /**
     * Create a controller specific setting Create a new controller specific settings object.
     * Requires admin access.
     *
     * @param controllerSetting A controller settings object to create (required)
     * @param headers Optional headers to include in the request
     * @return CompletableFuture&lt;CreateEnvelope&gt;
     * @throws ApiException if fails to make API call
     */
    public CompletableFuture<CreateEnvelope> createControllerSetting(
            @javax.annotation.Nonnull ControllerSettingCreate controllerSetting,
            Map<String, String> headers)
            throws ApiException {
        try {
            return createControllerSettingWithHttpInfo(controllerSetting, headers)
                    .thenApply(ApiResponse::getData);
        } catch (ApiException e) {
            return CompletableFuture.failedFuture(e);
        }
    }

    /**
     * Create a controller specific setting Create a new controller specific settings object.
     * Requires admin access.
     *
     * @param controllerSetting A controller settings object to create (required)
     * @return CompletableFuture&lt;ApiResponse&lt;CreateEnvelope&gt;&gt;
     * @throws ApiException if fails to make API call
     */
    public CompletableFuture<ApiResponse<CreateEnvelope>> createControllerSettingWithHttpInfo(
            @javax.annotation.Nonnull ControllerSettingCreate controllerSetting)
            throws ApiException {
        return createControllerSettingWithHttpInfo(controllerSetting, null);
    }

    /**
     * Create a controller specific setting Create a new controller specific settings object.
     * Requires admin access.
     *
     * @param controllerSetting A controller settings object to create (required)
     * @param headers Optional headers to include in the request
     * @return CompletableFuture&lt;ApiResponse&lt;CreateEnvelope&gt;&gt;
     * @throws ApiException if fails to make API call
     */
    public CompletableFuture<ApiResponse<CreateEnvelope>> createControllerSettingWithHttpInfo(
            @javax.annotation.Nonnull ControllerSettingCreate controllerSetting,
            Map<String, String> headers)
            throws ApiException {
        try {
            HttpRequest.Builder localVarRequestBuilder =
                    createControllerSettingRequestBuilder(controllerSetting, headers);
            return memberVarHttpClient
                    .sendAsync(
                            localVarRequestBuilder.build(),
                            HttpResponse.BodyHandlers.ofInputStream())
                    .thenComposeAsync(
                            localVarResponse -> {
                                if (memberVarAsyncResponseInterceptor != null) {
                                    memberVarAsyncResponseInterceptor.accept(localVarResponse);
                                }
                                if (localVarResponse.statusCode() / 100 != 2) {
                                    return CompletableFuture.failedFuture(
                                            getApiException(
                                                    "createControllerSetting", localVarResponse));
                                }
                                try {
                                    InputStream localVarResponseBody =
                                            ApiClient.getResponseBody(localVarResponse);
                                    try {
                                        if (localVarResponseBody == null) {
                                            return CompletableFuture.completedFuture(
                                                    new ApiResponse<CreateEnvelope>(
                                                            localVarResponse.statusCode(),
                                                            localVarResponse.headers().map(),
                                                            null));
                                        }

                                        String responseBody =
                                                new String(localVarResponseBody.readAllBytes());
                                        CreateEnvelope responseValue =
                                                responseBody.isBlank()
                                                        ? null
                                                        : memberVarObjectMapper.readValue(
                                                                responseBody,
                                                                new TypeReference<
                                                                        CreateEnvelope>() {});

                                        return CompletableFuture.completedFuture(
                                                new ApiResponse<CreateEnvelope>(
                                                        localVarResponse.statusCode(),
                                                        localVarResponse.headers().map(),
                                                        responseValue));
                                    } finally {
                                        if (localVarResponseBody != null) {
                                            localVarResponseBody.close();
                                        }
                                    }
                                } catch (IOException e) {
                                    return CompletableFuture.failedFuture(new ApiException(e));
                                }
                            });
        } catch (ApiException e) {
            return CompletableFuture.failedFuture(e);
        }
    }

    private HttpRequest.Builder createControllerSettingRequestBuilder(
            @javax.annotation.Nonnull ControllerSettingCreate controllerSetting,
            Map<String, String> headers)
            throws ApiException {
        // verify the required parameter 'controllerSetting' is set
        if (controllerSetting == null) {
            throw new ApiException(
                    400,
                    "Missing the required parameter 'controllerSetting' when calling"
                            + " createControllerSetting");
        }

        HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

        String localVarPath = "/controller-settings";

        localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

        localVarRequestBuilder.header("Content-Type", "application/json");
        localVarRequestBuilder.header("Accept", "application/json");

        try {
            byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(controllerSetting);
            localVarRequestBuilder.method(
                    "POST", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
        } catch (IOException e) {
            throw new ApiException(e);
        }
        if (memberVarReadTimeout != null) {
            localVarRequestBuilder.timeout(memberVarReadTimeout);
        }
        // Add custom headers if provided
        localVarRequestBuilder =
                HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
        if (memberVarInterceptor != null) {
            memberVarInterceptor.accept(localVarRequestBuilder);
        }
        return localVarRequestBuilder;
    }

    /**
     * Delete a controller setting object Delete a controller setting object by id. Requires admin
     * access.
     *
     * @param id The id of the requested resource (required)
     * @return CompletableFuture&lt;Empty&gt;
     * @throws ApiException if fails to make API call
     */
    public CompletableFuture<Empty> deleteControllerSetting(@javax.annotation.Nonnull String id)
            throws ApiException {
        return deleteControllerSetting(id, null);
    }

    /**
     * Delete a controller setting object Delete a controller setting object by id. Requires admin
     * access.
     *
     * @param id The id of the requested resource (required)
     * @param headers Optional headers to include in the request
     * @return CompletableFuture&lt;Empty&gt;
     * @throws ApiException if fails to make API call
     */
    public CompletableFuture<Empty> deleteControllerSetting(
            @javax.annotation.Nonnull String id, Map<String, String> headers) throws ApiException {
        try {
            return deleteControllerSettingWithHttpInfo(id, headers).thenApply(ApiResponse::getData);
        } catch (ApiException e) {
            return CompletableFuture.failedFuture(e);
        }
    }

    /**
     * Delete a controller setting object Delete a controller setting object by id. Requires admin
     * access.
     *
     * @param id The id of the requested resource (required)
     * @return CompletableFuture&lt;ApiResponse&lt;Empty&gt;&gt;
     * @throws ApiException if fails to make API call
     */
    public CompletableFuture<ApiResponse<Empty>> deleteControllerSettingWithHttpInfo(
            @javax.annotation.Nonnull String id) throws ApiException {
        return deleteControllerSettingWithHttpInfo(id, null);
    }

    /**
     * Delete a controller setting object Delete a controller setting object by id. Requires admin
     * access.
     *
     * @param id The id of the requested resource (required)
     * @param headers Optional headers to include in the request
     * @return CompletableFuture&lt;ApiResponse&lt;Empty&gt;&gt;
     * @throws ApiException if fails to make API call
     */
    public CompletableFuture<ApiResponse<Empty>> deleteControllerSettingWithHttpInfo(
            @javax.annotation.Nonnull String id, Map<String, String> headers) throws ApiException {
        try {
            HttpRequest.Builder localVarRequestBuilder =
                    deleteControllerSettingRequestBuilder(id, headers);
            return memberVarHttpClient
                    .sendAsync(
                            localVarRequestBuilder.build(),
                            HttpResponse.BodyHandlers.ofInputStream())
                    .thenComposeAsync(
                            localVarResponse -> {
                                if (memberVarAsyncResponseInterceptor != null) {
                                    memberVarAsyncResponseInterceptor.accept(localVarResponse);
                                }
                                if (localVarResponse.statusCode() / 100 != 2) {
                                    return CompletableFuture.failedFuture(
                                            getApiException(
                                                    "deleteControllerSetting", localVarResponse));
                                }
                                try {
                                    InputStream localVarResponseBody =
                                            ApiClient.getResponseBody(localVarResponse);
                                    try {
                                        if (localVarResponseBody == null) {
                                            return CompletableFuture.completedFuture(
                                                    new ApiResponse<Empty>(
                                                            localVarResponse.statusCode(),
                                                            localVarResponse.headers().map(),
                                                            null));
                                        }

                                        String responseBody =
                                                new String(localVarResponseBody.readAllBytes());
                                        Empty responseValue =
                                                responseBody.isBlank()
                                                        ? null
                                                        : memberVarObjectMapper.readValue(
                                                                responseBody,
                                                                new TypeReference<Empty>() {});

                                        return CompletableFuture.completedFuture(
                                                new ApiResponse<Empty>(
                                                        localVarResponse.statusCode(),
                                                        localVarResponse.headers().map(),
                                                        responseValue));
                                    } finally {
                                        if (localVarResponseBody != null) {
                                            localVarResponseBody.close();
                                        }
                                    }
                                } catch (IOException e) {
                                    return CompletableFuture.failedFuture(new ApiException(e));
                                }
                            });
        } catch (ApiException e) {
            return CompletableFuture.failedFuture(e);
        }
    }

    private HttpRequest.Builder deleteControllerSettingRequestBuilder(
            @javax.annotation.Nonnull String id, Map<String, String> headers) throws ApiException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException(
                    400,
                    "Missing the required parameter 'id' when calling deleteControllerSetting");
        }

        HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

        String localVarPath =
                "/controller-settings/{id}/effective"
                        .replace("{id}", ApiClient.urlEncode(id.toString()));

        localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

        localVarRequestBuilder.header("Accept", "application/json");

        localVarRequestBuilder.method("DELETE", HttpRequest.BodyPublishers.noBody());
        if (memberVarReadTimeout != null) {
            localVarRequestBuilder.timeout(memberVarReadTimeout);
        }
        // Add custom headers if provided
        localVarRequestBuilder =
                HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
        if (memberVarInterceptor != null) {
            memberVarInterceptor.accept(localVarRequestBuilder);
        }
        return localVarRequestBuilder;
    }

    /**
     * Retrieves a single controller setting object. Retrieves a single controller setting object by
     * id. Requires admin access.
     *
     * @param id The id of the requested resource (required)
     * @return CompletableFuture&lt;DetailControllerSettingEnvelope&gt;
     * @throws ApiException if fails to make API call
     */
    public CompletableFuture<DetailControllerSettingEnvelope> detailControllerSetting(
            @javax.annotation.Nonnull String id) throws ApiException {
        return detailControllerSetting(id, null);
    }

    /**
     * Retrieves a single controller setting object. Retrieves a single controller setting object by
     * id. Requires admin access.
     *
     * @param id The id of the requested resource (required)
     * @param headers Optional headers to include in the request
     * @return CompletableFuture&lt;DetailControllerSettingEnvelope&gt;
     * @throws ApiException if fails to make API call
     */
    public CompletableFuture<DetailControllerSettingEnvelope> detailControllerSetting(
            @javax.annotation.Nonnull String id, Map<String, String> headers) throws ApiException {
        try {
            return detailControllerSettingWithHttpInfo(id, headers).thenApply(ApiResponse::getData);
        } catch (ApiException e) {
            return CompletableFuture.failedFuture(e);
        }
    }

    /**
     * Retrieves a single controller setting object. Retrieves a single controller setting object by
     * id. Requires admin access.
     *
     * @param id The id of the requested resource (required)
     * @return CompletableFuture&lt;ApiResponse&lt;DetailControllerSettingEnvelope&gt;&gt;
     * @throws ApiException if fails to make API call
     */
    public CompletableFuture<ApiResponse<DetailControllerSettingEnvelope>>
            detailControllerSettingWithHttpInfo(@javax.annotation.Nonnull String id)
                    throws ApiException {
        return detailControllerSettingWithHttpInfo(id, null);
    }

    /**
     * Retrieves a single controller setting object. Retrieves a single controller setting object by
     * id. Requires admin access.
     *
     * @param id The id of the requested resource (required)
     * @param headers Optional headers to include in the request
     * @return CompletableFuture&lt;ApiResponse&lt;DetailControllerSettingEnvelope&gt;&gt;
     * @throws ApiException if fails to make API call
     */
    public CompletableFuture<ApiResponse<DetailControllerSettingEnvelope>>
            detailControllerSettingWithHttpInfo(
                    @javax.annotation.Nonnull String id, Map<String, String> headers)
                    throws ApiException {
        try {
            HttpRequest.Builder localVarRequestBuilder =
                    detailControllerSettingRequestBuilder(id, headers);
            return memberVarHttpClient
                    .sendAsync(
                            localVarRequestBuilder.build(),
                            HttpResponse.BodyHandlers.ofInputStream())
                    .thenComposeAsync(
                            localVarResponse -> {
                                if (memberVarAsyncResponseInterceptor != null) {
                                    memberVarAsyncResponseInterceptor.accept(localVarResponse);
                                }
                                if (localVarResponse.statusCode() / 100 != 2) {
                                    return CompletableFuture.failedFuture(
                                            getApiException(
                                                    "detailControllerSetting", localVarResponse));
                                }
                                try {
                                    InputStream localVarResponseBody =
                                            ApiClient.getResponseBody(localVarResponse);
                                    try {
                                        if (localVarResponseBody == null) {
                                            return CompletableFuture.completedFuture(
                                                    new ApiResponse<
                                                            DetailControllerSettingEnvelope>(
                                                            localVarResponse.statusCode(),
                                                            localVarResponse.headers().map(),
                                                            null));
                                        }

                                        String responseBody =
                                                new String(localVarResponseBody.readAllBytes());
                                        DetailControllerSettingEnvelope responseValue =
                                                responseBody.isBlank()
                                                        ? null
                                                        : memberVarObjectMapper.readValue(
                                                                responseBody,
                                                                new TypeReference<
                                                                        DetailControllerSettingEnvelope>() {});

                                        return CompletableFuture.completedFuture(
                                                new ApiResponse<DetailControllerSettingEnvelope>(
                                                        localVarResponse.statusCode(),
                                                        localVarResponse.headers().map(),
                                                        responseValue));
                                    } finally {
                                        if (localVarResponseBody != null) {
                                            localVarResponseBody.close();
                                        }
                                    }
                                } catch (IOException e) {
                                    return CompletableFuture.failedFuture(new ApiException(e));
                                }
                            });
        } catch (ApiException e) {
            return CompletableFuture.failedFuture(e);
        }
    }

    private HttpRequest.Builder detailControllerSettingRequestBuilder(
            @javax.annotation.Nonnull String id, Map<String, String> headers) throws ApiException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException(
                    400,
                    "Missing the required parameter 'id' when calling detailControllerSetting");
        }

        HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

        String localVarPath =
                "/controller-settings/{id}".replace("{id}", ApiClient.urlEncode(id.toString()));

        localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

        localVarRequestBuilder.header("Accept", "application/json");

        localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
        if (memberVarReadTimeout != null) {
            localVarRequestBuilder.timeout(memberVarReadTimeout);
        }
        // Add custom headers if provided
        localVarRequestBuilder =
                HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
        if (memberVarInterceptor != null) {
            memberVarInterceptor.accept(localVarRequestBuilder);
        }
        return localVarRequestBuilder;
    }

    /**
     * Retrieves a single controller&#39;s effective calculated settings from the instance and
     * global configuration. Retrieves a single controller&#39;s effective setting object by id.
     * Requires admin access.
     *
     * @param id The id of the requested resource (required)
     * @return CompletableFuture&lt;DetailControllerSettingEffectiveEnvelope&gt;
     * @throws ApiException if fails to make API call
     */
    public CompletableFuture<DetailControllerSettingEffectiveEnvelope>
            detailControllerSettingEffective(@javax.annotation.Nonnull String id)
                    throws ApiException {
        return detailControllerSettingEffective(id, null);
    }

    /**
     * Retrieves a single controller&#39;s effective calculated settings from the instance and
     * global configuration. Retrieves a single controller&#39;s effective setting object by id.
     * Requires admin access.
     *
     * @param id The id of the requested resource (required)
     * @param headers Optional headers to include in the request
     * @return CompletableFuture&lt;DetailControllerSettingEffectiveEnvelope&gt;
     * @throws ApiException if fails to make API call
     */
    public CompletableFuture<DetailControllerSettingEffectiveEnvelope>
            detailControllerSettingEffective(
                    @javax.annotation.Nonnull String id, Map<String, String> headers)
                    throws ApiException {
        try {
            return detailControllerSettingEffectiveWithHttpInfo(id, headers)
                    .thenApply(ApiResponse::getData);
        } catch (ApiException e) {
            return CompletableFuture.failedFuture(e);
        }
    }

    /**
     * Retrieves a single controller&#39;s effective calculated settings from the instance and
     * global configuration. Retrieves a single controller&#39;s effective setting object by id.
     * Requires admin access.
     *
     * @param id The id of the requested resource (required)
     * @return CompletableFuture&lt;ApiResponse&lt;DetailControllerSettingEffectiveEnvelope&gt;&gt;
     * @throws ApiException if fails to make API call
     */
    public CompletableFuture<ApiResponse<DetailControllerSettingEffectiveEnvelope>>
            detailControllerSettingEffectiveWithHttpInfo(@javax.annotation.Nonnull String id)
                    throws ApiException {
        return detailControllerSettingEffectiveWithHttpInfo(id, null);
    }

    /**
     * Retrieves a single controller&#39;s effective calculated settings from the instance and
     * global configuration. Retrieves a single controller&#39;s effective setting object by id.
     * Requires admin access.
     *
     * @param id The id of the requested resource (required)
     * @param headers Optional headers to include in the request
     * @return CompletableFuture&lt;ApiResponse&lt;DetailControllerSettingEffectiveEnvelope&gt;&gt;
     * @throws ApiException if fails to make API call
     */
    public CompletableFuture<ApiResponse<DetailControllerSettingEffectiveEnvelope>>
            detailControllerSettingEffectiveWithHttpInfo(
                    @javax.annotation.Nonnull String id, Map<String, String> headers)
                    throws ApiException {
        try {
            HttpRequest.Builder localVarRequestBuilder =
                    detailControllerSettingEffectiveRequestBuilder(id, headers);
            return memberVarHttpClient
                    .sendAsync(
                            localVarRequestBuilder.build(),
                            HttpResponse.BodyHandlers.ofInputStream())
                    .thenComposeAsync(
                            localVarResponse -> {
                                if (memberVarAsyncResponseInterceptor != null) {
                                    memberVarAsyncResponseInterceptor.accept(localVarResponse);
                                }
                                if (localVarResponse.statusCode() / 100 != 2) {
                                    return CompletableFuture.failedFuture(
                                            getApiException(
                                                    "detailControllerSettingEffective",
                                                    localVarResponse));
                                }
                                try {
                                    InputStream localVarResponseBody =
                                            ApiClient.getResponseBody(localVarResponse);
                                    try {
                                        if (localVarResponseBody == null) {
                                            return CompletableFuture.completedFuture(
                                                    new ApiResponse<
                                                            DetailControllerSettingEffectiveEnvelope>(
                                                            localVarResponse.statusCode(),
                                                            localVarResponse.headers().map(),
                                                            null));
                                        }

                                        String responseBody =
                                                new String(localVarResponseBody.readAllBytes());
                                        DetailControllerSettingEffectiveEnvelope responseValue =
                                                responseBody.isBlank()
                                                        ? null
                                                        : memberVarObjectMapper.readValue(
                                                                responseBody,
                                                                new TypeReference<
                                                                        DetailControllerSettingEffectiveEnvelope>() {});

                                        return CompletableFuture.completedFuture(
                                                new ApiResponse<
                                                        DetailControllerSettingEffectiveEnvelope>(
                                                        localVarResponse.statusCode(),
                                                        localVarResponse.headers().map(),
                                                        responseValue));
                                    } finally {
                                        if (localVarResponseBody != null) {
                                            localVarResponseBody.close();
                                        }
                                    }
                                } catch (IOException e) {
                                    return CompletableFuture.failedFuture(new ApiException(e));
                                }
                            });
        } catch (ApiException e) {
            return CompletableFuture.failedFuture(e);
        }
    }

    private HttpRequest.Builder detailControllerSettingEffectiveRequestBuilder(
            @javax.annotation.Nonnull String id, Map<String, String> headers) throws ApiException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException(
                    400,
                    "Missing the required parameter 'id' when calling"
                            + " detailControllerSettingEffective");
        }

        HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

        String localVarPath =
                "/controller-settings/{id}/effective"
                        .replace("{id}", ApiClient.urlEncode(id.toString()));

        localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

        localVarRequestBuilder.header("Accept", "application/json");

        localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
        if (memberVarReadTimeout != null) {
            localVarRequestBuilder.timeout(memberVarReadTimeout);
        }
        // Add custom headers if provided
        localVarRequestBuilder =
                HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
        if (memberVarInterceptor != null) {
            memberVarInterceptor.accept(localVarRequestBuilder);
        }
        return localVarRequestBuilder;
    }

    /**
     * List controller settings Retrieves a list controller settings including the base
     * &#x60;global&#x60; settings object and any overriding controller specific settings.
     *
     * @param limit (optional)
     * @param offset (optional)
     * @param filter (optional)
     * @return CompletableFuture&lt;ListControllerSettingEnvelope&gt;
     * @throws ApiException if fails to make API call
     */
    public CompletableFuture<ListControllerSettingEnvelope> listControllerSettings(
            @javax.annotation.Nullable Integer limit,
            @javax.annotation.Nullable Integer offset,
            @javax.annotation.Nullable String filter)
            throws ApiException {
        return listControllerSettings(limit, offset, filter, null);
    }

    /**
     * List controller settings Retrieves a list controller settings including the base
     * &#x60;global&#x60; settings object and any overriding controller specific settings.
     *
     * @param limit (optional)
     * @param offset (optional)
     * @param filter (optional)
     * @param headers Optional headers to include in the request
     * @return CompletableFuture&lt;ListControllerSettingEnvelope&gt;
     * @throws ApiException if fails to make API call
     */
    public CompletableFuture<ListControllerSettingEnvelope> listControllerSettings(
            @javax.annotation.Nullable Integer limit,
            @javax.annotation.Nullable Integer offset,
            @javax.annotation.Nullable String filter,
            Map<String, String> headers)
            throws ApiException {
        try {
            return listControllerSettingsWithHttpInfo(limit, offset, filter, headers)
                    .thenApply(ApiResponse::getData);
        } catch (ApiException e) {
            return CompletableFuture.failedFuture(e);
        }
    }

    /**
     * List controller settings Retrieves a list controller settings including the base
     * &#x60;global&#x60; settings object and any overriding controller specific settings.
     *
     * @param limit (optional)
     * @param offset (optional)
     * @param filter (optional)
     * @return CompletableFuture&lt;ApiResponse&lt;ListControllerSettingEnvelope&gt;&gt;
     * @throws ApiException if fails to make API call
     */
    public CompletableFuture<ApiResponse<ListControllerSettingEnvelope>>
            listControllerSettingsWithHttpInfo(
                    @javax.annotation.Nullable Integer limit,
                    @javax.annotation.Nullable Integer offset,
                    @javax.annotation.Nullable String filter)
                    throws ApiException {
        return listControllerSettingsWithHttpInfo(limit, offset, filter, null);
    }

    /**
     * List controller settings Retrieves a list controller settings including the base
     * &#x60;global&#x60; settings object and any overriding controller specific settings.
     *
     * @param limit (optional)
     * @param offset (optional)
     * @param filter (optional)
     * @param headers Optional headers to include in the request
     * @return CompletableFuture&lt;ApiResponse&lt;ListControllerSettingEnvelope&gt;&gt;
     * @throws ApiException if fails to make API call
     */
    public CompletableFuture<ApiResponse<ListControllerSettingEnvelope>>
            listControllerSettingsWithHttpInfo(
                    @javax.annotation.Nullable Integer limit,
                    @javax.annotation.Nullable Integer offset,
                    @javax.annotation.Nullable String filter,
                    Map<String, String> headers)
                    throws ApiException {
        try {
            HttpRequest.Builder localVarRequestBuilder =
                    listControllerSettingsRequestBuilder(limit, offset, filter, headers);
            return memberVarHttpClient
                    .sendAsync(
                            localVarRequestBuilder.build(),
                            HttpResponse.BodyHandlers.ofInputStream())
                    .thenComposeAsync(
                            localVarResponse -> {
                                if (memberVarAsyncResponseInterceptor != null) {
                                    memberVarAsyncResponseInterceptor.accept(localVarResponse);
                                }
                                if (localVarResponse.statusCode() / 100 != 2) {
                                    return CompletableFuture.failedFuture(
                                            getApiException(
                                                    "listControllerSettings", localVarResponse));
                                }
                                try {
                                    InputStream localVarResponseBody =
                                            ApiClient.getResponseBody(localVarResponse);
                                    try {
                                        if (localVarResponseBody == null) {
                                            return CompletableFuture.completedFuture(
                                                    new ApiResponse<ListControllerSettingEnvelope>(
                                                            localVarResponse.statusCode(),
                                                            localVarResponse.headers().map(),
                                                            null));
                                        }

                                        String responseBody =
                                                new String(localVarResponseBody.readAllBytes());
                                        ListControllerSettingEnvelope responseValue =
                                                responseBody.isBlank()
                                                        ? null
                                                        : memberVarObjectMapper.readValue(
                                                                responseBody,
                                                                new TypeReference<
                                                                        ListControllerSettingEnvelope>() {});

                                        return CompletableFuture.completedFuture(
                                                new ApiResponse<ListControllerSettingEnvelope>(
                                                        localVarResponse.statusCode(),
                                                        localVarResponse.headers().map(),
                                                        responseValue));
                                    } finally {
                                        if (localVarResponseBody != null) {
                                            localVarResponseBody.close();
                                        }
                                    }
                                } catch (IOException e) {
                                    return CompletableFuture.failedFuture(new ApiException(e));
                                }
                            });
        } catch (ApiException e) {
            return CompletableFuture.failedFuture(e);
        }
    }

    private HttpRequest.Builder listControllerSettingsRequestBuilder(
            @javax.annotation.Nullable Integer limit,
            @javax.annotation.Nullable Integer offset,
            @javax.annotation.Nullable String filter,
            Map<String, String> headers)
            throws ApiException {

        HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

        String localVarPath = "/controller-settings";

        List<Pair> localVarQueryParams = new ArrayList<>();
        StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
        String localVarQueryParameterBaseName;
        localVarQueryParameterBaseName = "limit";
        localVarQueryParams.addAll(ApiClient.parameterToPairs("limit", limit));
        localVarQueryParameterBaseName = "offset";
        localVarQueryParams.addAll(ApiClient.parameterToPairs("offset", offset));
        localVarQueryParameterBaseName = "filter";
        localVarQueryParams.addAll(ApiClient.parameterToPairs("filter", filter));

        if (!localVarQueryParams.isEmpty() || localVarQueryStringJoiner.length() != 0) {
            StringJoiner queryJoiner = new StringJoiner("&");
            localVarQueryParams.forEach(p -> queryJoiner.add(p.getName() + '=' + p.getValue()));
            if (localVarQueryStringJoiner.length() != 0) {
                queryJoiner.add(localVarQueryStringJoiner.toString());
            }
            localVarRequestBuilder.uri(
                    URI.create(memberVarBaseUri + localVarPath + '?' + queryJoiner.toString()));
        } else {
            localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));
        }

        localVarRequestBuilder.header("Accept", "application/json");

        localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
        if (memberVarReadTimeout != null) {
            localVarRequestBuilder.timeout(memberVarReadTimeout);
        }
        // Add custom headers if provided
        localVarRequestBuilder =
                HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
        if (memberVarInterceptor != null) {
            memberVarInterceptor.accept(localVarRequestBuilder);
        }
        return localVarRequestBuilder;
    }

    /**
     * Update the supplied fields on a controller setting object Update the supplied fields on a
     * controller setting object. Requires admin access.
     *
     * @param id The id of the requested resource (required)
     * @param controllerSetting A controller setting object patch object (required)
     * @return CompletableFuture&lt;Empty&gt;
     * @throws ApiException if fails to make API call
     */
    public CompletableFuture<Empty> patchControllerSetting(
            @javax.annotation.Nonnull String id,
            @javax.annotation.Nonnull ControllerSettingPatch controllerSetting)
            throws ApiException {
        return patchControllerSetting(id, controllerSetting, null);
    }

    /**
     * Update the supplied fields on a controller setting object Update the supplied fields on a
     * controller setting object. Requires admin access.
     *
     * @param id The id of the requested resource (required)
     * @param controllerSetting A controller setting object patch object (required)
     * @param headers Optional headers to include in the request
     * @return CompletableFuture&lt;Empty&gt;
     * @throws ApiException if fails to make API call
     */
    public CompletableFuture<Empty> patchControllerSetting(
            @javax.annotation.Nonnull String id,
            @javax.annotation.Nonnull ControllerSettingPatch controllerSetting,
            Map<String, String> headers)
            throws ApiException {
        try {
            return patchControllerSettingWithHttpInfo(id, controllerSetting, headers)
                    .thenApply(ApiResponse::getData);
        } catch (ApiException e) {
            return CompletableFuture.failedFuture(e);
        }
    }

    /**
     * Update the supplied fields on a controller setting object Update the supplied fields on a
     * controller setting object. Requires admin access.
     *
     * @param id The id of the requested resource (required)
     * @param controllerSetting A controller setting object patch object (required)
     * @return CompletableFuture&lt;ApiResponse&lt;Empty&gt;&gt;
     * @throws ApiException if fails to make API call
     */
    public CompletableFuture<ApiResponse<Empty>> patchControllerSettingWithHttpInfo(
            @javax.annotation.Nonnull String id,
            @javax.annotation.Nonnull ControllerSettingPatch controllerSetting)
            throws ApiException {
        return patchControllerSettingWithHttpInfo(id, controllerSetting, null);
    }

    /**
     * Update the supplied fields on a controller setting object Update the supplied fields on a
     * controller setting object. Requires admin access.
     *
     * @param id The id of the requested resource (required)
     * @param controllerSetting A controller setting object patch object (required)
     * @param headers Optional headers to include in the request
     * @return CompletableFuture&lt;ApiResponse&lt;Empty&gt;&gt;
     * @throws ApiException if fails to make API call
     */
    public CompletableFuture<ApiResponse<Empty>> patchControllerSettingWithHttpInfo(
            @javax.annotation.Nonnull String id,
            @javax.annotation.Nonnull ControllerSettingPatch controllerSetting,
            Map<String, String> headers)
            throws ApiException {
        try {
            HttpRequest.Builder localVarRequestBuilder =
                    patchControllerSettingRequestBuilder(id, controllerSetting, headers);
            return memberVarHttpClient
                    .sendAsync(
                            localVarRequestBuilder.build(),
                            HttpResponse.BodyHandlers.ofInputStream())
                    .thenComposeAsync(
                            localVarResponse -> {
                                if (memberVarAsyncResponseInterceptor != null) {
                                    memberVarAsyncResponseInterceptor.accept(localVarResponse);
                                }
                                if (localVarResponse.statusCode() / 100 != 2) {
                                    return CompletableFuture.failedFuture(
                                            getApiException(
                                                    "patchControllerSetting", localVarResponse));
                                }
                                try {
                                    InputStream localVarResponseBody =
                                            ApiClient.getResponseBody(localVarResponse);
                                    try {
                                        if (localVarResponseBody == null) {
                                            return CompletableFuture.completedFuture(
                                                    new ApiResponse<Empty>(
                                                            localVarResponse.statusCode(),
                                                            localVarResponse.headers().map(),
                                                            null));
                                        }

                                        String responseBody =
                                                new String(localVarResponseBody.readAllBytes());
                                        Empty responseValue =
                                                responseBody.isBlank()
                                                        ? null
                                                        : memberVarObjectMapper.readValue(
                                                                responseBody,
                                                                new TypeReference<Empty>() {});

                                        return CompletableFuture.completedFuture(
                                                new ApiResponse<Empty>(
                                                        localVarResponse.statusCode(),
                                                        localVarResponse.headers().map(),
                                                        responseValue));
                                    } finally {
                                        if (localVarResponseBody != null) {
                                            localVarResponseBody.close();
                                        }
                                    }
                                } catch (IOException e) {
                                    return CompletableFuture.failedFuture(new ApiException(e));
                                }
                            });
        } catch (ApiException e) {
            return CompletableFuture.failedFuture(e);
        }
    }

    private HttpRequest.Builder patchControllerSettingRequestBuilder(
            @javax.annotation.Nonnull String id,
            @javax.annotation.Nonnull ControllerSettingPatch controllerSetting,
            Map<String, String> headers)
            throws ApiException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException(
                    400, "Missing the required parameter 'id' when calling patchControllerSetting");
        }
        // verify the required parameter 'controllerSetting' is set
        if (controllerSetting == null) {
            throw new ApiException(
                    400,
                    "Missing the required parameter 'controllerSetting' when calling"
                            + " patchControllerSetting");
        }

        HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

        String localVarPath =
                "/controller-settings/{id}/effective"
                        .replace("{id}", ApiClient.urlEncode(id.toString()));

        localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

        localVarRequestBuilder.header("Content-Type", "application/json");
        localVarRequestBuilder.header("Accept", "application/json");

        try {
            byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(controllerSetting);
            localVarRequestBuilder.method(
                    "PATCH", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
        } catch (IOException e) {
            throw new ApiException(e);
        }
        if (memberVarReadTimeout != null) {
            localVarRequestBuilder.timeout(memberVarReadTimeout);
        }
        // Add custom headers if provided
        localVarRequestBuilder =
                HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
        if (memberVarInterceptor != null) {
            memberVarInterceptor.accept(localVarRequestBuilder);
        }
        return localVarRequestBuilder;
    }

    /**
     * Update all fields on a controller setting object Update all fields on a controller setting
     * object by id. Requires admin access.
     *
     * @param id The id of the requested resource (required)
     * @param controllerSetting A controller setting update object (required)
     * @return CompletableFuture&lt;Empty&gt;
     * @throws ApiException if fails to make API call
     */
    public CompletableFuture<Empty> updateControllerSetting(
            @javax.annotation.Nonnull String id,
            @javax.annotation.Nonnull ControllerSettingUpdate controllerSetting)
            throws ApiException {
        return updateControllerSetting(id, controllerSetting, null);
    }

    /**
     * Update all fields on a controller setting object Update all fields on a controller setting
     * object by id. Requires admin access.
     *
     * @param id The id of the requested resource (required)
     * @param controllerSetting A controller setting update object (required)
     * @param headers Optional headers to include in the request
     * @return CompletableFuture&lt;Empty&gt;
     * @throws ApiException if fails to make API call
     */
    public CompletableFuture<Empty> updateControllerSetting(
            @javax.annotation.Nonnull String id,
            @javax.annotation.Nonnull ControllerSettingUpdate controllerSetting,
            Map<String, String> headers)
            throws ApiException {
        try {
            return updateControllerSettingWithHttpInfo(id, controllerSetting, headers)
                    .thenApply(ApiResponse::getData);
        } catch (ApiException e) {
            return CompletableFuture.failedFuture(e);
        }
    }

    /**
     * Update all fields on a controller setting object Update all fields on a controller setting
     * object by id. Requires admin access.
     *
     * @param id The id of the requested resource (required)
     * @param controllerSetting A controller setting update object (required)
     * @return CompletableFuture&lt;ApiResponse&lt;Empty&gt;&gt;
     * @throws ApiException if fails to make API call
     */
    public CompletableFuture<ApiResponse<Empty>> updateControllerSettingWithHttpInfo(
            @javax.annotation.Nonnull String id,
            @javax.annotation.Nonnull ControllerSettingUpdate controllerSetting)
            throws ApiException {
        return updateControllerSettingWithHttpInfo(id, controllerSetting, null);
    }

    /**
     * Update all fields on a controller setting object Update all fields on a controller setting
     * object by id. Requires admin access.
     *
     * @param id The id of the requested resource (required)
     * @param controllerSetting A controller setting update object (required)
     * @param headers Optional headers to include in the request
     * @return CompletableFuture&lt;ApiResponse&lt;Empty&gt;&gt;
     * @throws ApiException if fails to make API call
     */
    public CompletableFuture<ApiResponse<Empty>> updateControllerSettingWithHttpInfo(
            @javax.annotation.Nonnull String id,
            @javax.annotation.Nonnull ControllerSettingUpdate controllerSetting,
            Map<String, String> headers)
            throws ApiException {
        try {
            HttpRequest.Builder localVarRequestBuilder =
                    updateControllerSettingRequestBuilder(id, controllerSetting, headers);
            return memberVarHttpClient
                    .sendAsync(
                            localVarRequestBuilder.build(),
                            HttpResponse.BodyHandlers.ofInputStream())
                    .thenComposeAsync(
                            localVarResponse -> {
                                if (memberVarAsyncResponseInterceptor != null) {
                                    memberVarAsyncResponseInterceptor.accept(localVarResponse);
                                }
                                if (localVarResponse.statusCode() / 100 != 2) {
                                    return CompletableFuture.failedFuture(
                                            getApiException(
                                                    "updateControllerSetting", localVarResponse));
                                }
                                try {
                                    InputStream localVarResponseBody =
                                            ApiClient.getResponseBody(localVarResponse);
                                    try {
                                        if (localVarResponseBody == null) {
                                            return CompletableFuture.completedFuture(
                                                    new ApiResponse<Empty>(
                                                            localVarResponse.statusCode(),
                                                            localVarResponse.headers().map(),
                                                            null));
                                        }

                                        String responseBody =
                                                new String(localVarResponseBody.readAllBytes());
                                        Empty responseValue =
                                                responseBody.isBlank()
                                                        ? null
                                                        : memberVarObjectMapper.readValue(
                                                                responseBody,
                                                                new TypeReference<Empty>() {});

                                        return CompletableFuture.completedFuture(
                                                new ApiResponse<Empty>(
                                                        localVarResponse.statusCode(),
                                                        localVarResponse.headers().map(),
                                                        responseValue));
                                    } finally {
                                        if (localVarResponseBody != null) {
                                            localVarResponseBody.close();
                                        }
                                    }
                                } catch (IOException e) {
                                    return CompletableFuture.failedFuture(new ApiException(e));
                                }
                            });
        } catch (ApiException e) {
            return CompletableFuture.failedFuture(e);
        }
    }

    private HttpRequest.Builder updateControllerSettingRequestBuilder(
            @javax.annotation.Nonnull String id,
            @javax.annotation.Nonnull ControllerSettingUpdate controllerSetting,
            Map<String, String> headers)
            throws ApiException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException(
                    400,
                    "Missing the required parameter 'id' when calling updateControllerSetting");
        }
        // verify the required parameter 'controllerSetting' is set
        if (controllerSetting == null) {
            throw new ApiException(
                    400,
                    "Missing the required parameter 'controllerSetting' when calling"
                            + " updateControllerSetting");
        }

        HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

        String localVarPath =
                "/controller-settings/{id}/effective"
                        .replace("{id}", ApiClient.urlEncode(id.toString()));

        localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

        localVarRequestBuilder.header("Content-Type", "application/json");
        localVarRequestBuilder.header("Accept", "application/json");

        try {
            byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(controllerSetting);
            localVarRequestBuilder.method(
                    "PUT", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
        } catch (IOException e) {
            throw new ApiException(e);
        }
        if (memberVarReadTimeout != null) {
            localVarRequestBuilder.timeout(memberVarReadTimeout);
        }
        // Add custom headers if provided
        localVarRequestBuilder =
                HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
        if (memberVarInterceptor != null) {
            memberVarInterceptor.accept(localVarRequestBuilder);
        }
        return localVarRequestBuilder;
    }
}
