/*
 * Ziti Edge Management
 * OpenZiti Edge Management API
 *
 * The version of the OpenAPI document: 0.31.0
 * Contact: help@openziti.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openziti.management.api;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.time.Duration;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.StringJoiner;
import java.util.concurrent.CompletableFuture;
import java.util.function.Consumer;
import org.openziti.management.ApiClient;
import org.openziti.management.ApiException;
import org.openziti.management.ApiResponse;
import org.openziti.management.Configuration;
import org.openziti.management.Pair;
import org.openziti.management.model.CreateEnvelope;
import org.openziti.management.model.DetailTerminatorEnvelope;
import org.openziti.management.model.Empty;
import org.openziti.management.model.ListTerminatorsEnvelope;
import org.openziti.management.model.TerminatorCreate;
import org.openziti.management.model.TerminatorPatch;
import org.openziti.management.model.TerminatorUpdate;

@javax.annotation.Generated(
        value = "org.openapitools.codegen.languages.JavaClientCodegen",
        date = "2026-06-04T09:00:03.854034-04:00[America/New_York]",
        comments = "Generator version: 7.22.0")
public class TerminatorApi {
    /** Utility class for extending HttpRequest.Builder functionality. */
    private static class HttpRequestBuilderExtensions {
        /**
         * Adds additional headers to the provided HttpRequest.Builder. Useful for adding
         * method/endpoint specific headers.
         *
         * @param builder the HttpRequest.Builder to which headers will be added
         * @param headers a map of header names and values to add; may be null
         * @return the same HttpRequest.Builder instance with the additional headers set
         */
        static HttpRequest.Builder withAdditionalHeaders(
                HttpRequest.Builder builder, Map<String, String> headers) {
            if (headers != null) {
                for (Map.Entry<String, String> entry : headers.entrySet()) {
                    builder.header(entry.getKey(), entry.getValue());
                }
            }
            return builder;
        }
    }

    private final HttpClient memberVarHttpClient;
    private final ObjectMapper memberVarObjectMapper;
    private final String memberVarBaseUri;
    private final Consumer<HttpRequest.Builder> memberVarInterceptor;
    private final Duration memberVarReadTimeout;
    private final Consumer<HttpResponse<InputStream>> memberVarResponseInterceptor;
    private final Consumer<HttpResponse<InputStream>> memberVarAsyncResponseInterceptor;

    public TerminatorApi() {
        this(Configuration.getDefaultApiClient());
    }

    public TerminatorApi(ApiClient apiClient) {
        memberVarHttpClient = apiClient.getHttpClient();
        memberVarObjectMapper = apiClient.getObjectMapper();
        memberVarBaseUri = apiClient.getBaseUri();
        memberVarInterceptor = apiClient.getRequestInterceptor();
        memberVarReadTimeout = apiClient.getReadTimeout();
        memberVarResponseInterceptor = apiClient.getResponseInterceptor();
        memberVarAsyncResponseInterceptor = apiClient.getAsyncResponseInterceptor();
    }

    private ApiException getApiException(String operationId, HttpResponse<InputStream> response) {
        try {
            InputStream responseBody = ApiClient.getResponseBody(response);
            String body = null;
            if (responseBody != null) {
                body = new String(responseBody.readAllBytes());
                responseBody.close();
            }
            String message = formatExceptionMessage(operationId, response.statusCode(), body);
            return new ApiException(response.statusCode(), message, response.headers(), body);
        } catch (IOException e) {
            return new ApiException(e);
        }
    }

    private String formatExceptionMessage(String operationId, int statusCode, String body) {
        if (body == null || body.isEmpty()) {
            body = "[no body]";
        }
        return operationId + " call failed with: " + statusCode + " - " + body;
    }

    /**
     * Download file from the given response.
     *
     * @param response Response
     * @return File
     * @throws ApiException If fail to read file content from response and write to disk
     */
    public File downloadFileFromResponse(
            HttpResponse<InputStream> response, InputStream responseBody) throws ApiException {
        if (responseBody == null) {
            throw new ApiException(new IOException("Response body is empty"));
        }
        try {
            File file = prepareDownloadFile(response);
            java.nio.file.Files.copy(
                    responseBody, file.toPath(), java.nio.file.StandardCopyOption.REPLACE_EXISTING);
            return file;
        } catch (IOException e) {
            throw new ApiException(e);
        }
    }

    /**
     * Prepare the file for download from the response.
     *
     * @param response a {@link java.net.http.HttpResponse} object.
     * @return a {@link java.io.File} object.
     * @throws java.io.IOException if any.
     */
    private File prepareDownloadFile(HttpResponse<InputStream> response) throws IOException {
        String filename = null;
        java.util.Optional<String> contentDisposition =
                response.headers().firstValue("Content-Disposition");
        if (contentDisposition.isPresent() && !"".equals(contentDisposition.get())) {
            // Get filename from the Content-Disposition header.
            java.util.regex.Pattern pattern =
                    java.util.regex.Pattern.compile("filename=['\"]?([^'\"\\s]+)['\"]?");
            java.util.regex.Matcher matcher = pattern.matcher(contentDisposition.get());
            if (matcher.find()) filename = matcher.group(1);
        }
        File file = null;
        if (filename != null) {
            java.nio.file.Path tempDir =
                    java.nio.file.Files.createTempDirectory("swagger-gen-native");
            java.nio.file.Path filePath = java.nio.file.Files.createFile(tempDir.resolve(filename));
            file = filePath.toFile();
            tempDir.toFile().deleteOnExit(); // best effort cleanup
            file.deleteOnExit(); // best effort cleanup
        } else {
            file = java.nio.file.Files.createTempFile("download-", "").toFile();
            file.deleteOnExit(); // best effort cleanup
        }
        return file;
    }

    /**
     * Create a terminator resource Create a terminator resource. Requires admin access.
     *
     * @param terminator A terminator to create (required)
     * @return CompletableFuture&lt;CreateEnvelope&gt;
     * @throws ApiException if fails to make API call
     */
    public CompletableFuture<CreateEnvelope> createTerminator(
            @javax.annotation.Nonnull TerminatorCreate terminator) throws ApiException {
        return createTerminator(terminator, null);
    }

    /**
     * Create a terminator resource Create a terminator resource. Requires admin access.
     *
     * @param terminator A terminator to create (required)
     * @param headers Optional headers to include in the request
     * @return CompletableFuture&lt;CreateEnvelope&gt;
     * @throws ApiException if fails to make API call
     */
    public CompletableFuture<CreateEnvelope> createTerminator(
            @javax.annotation.Nonnull TerminatorCreate terminator, Map<String, String> headers)
            throws ApiException {
        try {
            return createTerminatorWithHttpInfo(terminator, headers)
                    .thenApply(ApiResponse::getData);
        } catch (ApiException e) {
            return CompletableFuture.failedFuture(e);
        }
    }

    /**
     * Create a terminator resource Create a terminator resource. Requires admin access.
     *
     * @param terminator A terminator to create (required)
     * @return CompletableFuture&lt;ApiResponse&lt;CreateEnvelope&gt;&gt;
     * @throws ApiException if fails to make API call
     */
    public CompletableFuture<ApiResponse<CreateEnvelope>> createTerminatorWithHttpInfo(
            @javax.annotation.Nonnull TerminatorCreate terminator) throws ApiException {
        return createTerminatorWithHttpInfo(terminator, null);
    }

    /**
     * Create a terminator resource Create a terminator resource. Requires admin access.
     *
     * @param terminator A terminator to create (required)
     * @param headers Optional headers to include in the request
     * @return CompletableFuture&lt;ApiResponse&lt;CreateEnvelope&gt;&gt;
     * @throws ApiException if fails to make API call
     */
    public CompletableFuture<ApiResponse<CreateEnvelope>> createTerminatorWithHttpInfo(
            @javax.annotation.Nonnull TerminatorCreate terminator, Map<String, String> headers)
            throws ApiException {
        try {
            HttpRequest.Builder localVarRequestBuilder =
                    createTerminatorRequestBuilder(terminator, headers);
            return memberVarHttpClient
                    .sendAsync(
                            localVarRequestBuilder.build(),
                            HttpResponse.BodyHandlers.ofInputStream())
                    .thenComposeAsync(
                            localVarResponse -> {
                                if (memberVarAsyncResponseInterceptor != null) {
                                    memberVarAsyncResponseInterceptor.accept(localVarResponse);
                                }
                                if (localVarResponse.statusCode() / 100 != 2) {
                                    return CompletableFuture.failedFuture(
                                            getApiException("createTerminator", localVarResponse));
                                }
                                try {
                                    InputStream localVarResponseBody =
                                            ApiClient.getResponseBody(localVarResponse);
                                    try {
                                        if (localVarResponseBody == null) {
                                            return CompletableFuture.completedFuture(
                                                    new ApiResponse<CreateEnvelope>(
                                                            localVarResponse.statusCode(),
                                                            localVarResponse.headers().map(),
                                                            null));
                                        }

                                        String responseBody =
                                                new String(localVarResponseBody.readAllBytes());
                                        CreateEnvelope responseValue =
                                                responseBody.isBlank()
                                                        ? null
                                                        : memberVarObjectMapper.readValue(
                                                                responseBody,
                                                                new TypeReference<
                                                                        CreateEnvelope>() {});

                                        return CompletableFuture.completedFuture(
                                                new ApiResponse<CreateEnvelope>(
                                                        localVarResponse.statusCode(),
                                                        localVarResponse.headers().map(),
                                                        responseValue));
                                    } finally {
                                        if (localVarResponseBody != null) {
                                            localVarResponseBody.close();
                                        }
                                    }
                                } catch (IOException e) {
                                    return CompletableFuture.failedFuture(new ApiException(e));
                                }
                            });
        } catch (ApiException e) {
            return CompletableFuture.failedFuture(e);
        }
    }

    private HttpRequest.Builder createTerminatorRequestBuilder(
            @javax.annotation.Nonnull TerminatorCreate terminator, Map<String, String> headers)
            throws ApiException {
        // verify the required parameter 'terminator' is set
        if (terminator == null) {
            throw new ApiException(
                    400,
                    "Missing the required parameter 'terminator' when calling createTerminator");
        }

        HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

        String localVarPath = "/terminators";

        localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

        localVarRequestBuilder.header("Content-Type", "application/json");
        localVarRequestBuilder.header("Accept", "application/json");

        try {
            byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(terminator);
            localVarRequestBuilder.method(
                    "POST", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
        } catch (IOException e) {
            throw new ApiException(e);
        }
        if (memberVarReadTimeout != null) {
            localVarRequestBuilder.timeout(memberVarReadTimeout);
        }
        // Add custom headers if provided
        localVarRequestBuilder =
                HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
        if (memberVarInterceptor != null) {
            memberVarInterceptor.accept(localVarRequestBuilder);
        }
        return localVarRequestBuilder;
    }

    /**
     * Delete a terminator Delete a terminator by id. Requires admin access.
     *
     * @param id The id of the requested resource (required)
     * @return CompletableFuture&lt;Empty&gt;
     * @throws ApiException if fails to make API call
     */
    public CompletableFuture<Empty> deleteTerminator(@javax.annotation.Nonnull String id)
            throws ApiException {
        return deleteTerminator(id, null);
    }

    /**
     * Delete a terminator Delete a terminator by id. Requires admin access.
     *
     * @param id The id of the requested resource (required)
     * @param headers Optional headers to include in the request
     * @return CompletableFuture&lt;Empty&gt;
     * @throws ApiException if fails to make API call
     */
    public CompletableFuture<Empty> deleteTerminator(
            @javax.annotation.Nonnull String id, Map<String, String> headers) throws ApiException {
        try {
            return deleteTerminatorWithHttpInfo(id, headers).thenApply(ApiResponse::getData);
        } catch (ApiException e) {
            return CompletableFuture.failedFuture(e);
        }
    }

    /**
     * Delete a terminator Delete a terminator by id. Requires admin access.
     *
     * @param id The id of the requested resource (required)
     * @return CompletableFuture&lt;ApiResponse&lt;Empty&gt;&gt;
     * @throws ApiException if fails to make API call
     */
    public CompletableFuture<ApiResponse<Empty>> deleteTerminatorWithHttpInfo(
            @javax.annotation.Nonnull String id) throws ApiException {
        return deleteTerminatorWithHttpInfo(id, null);
    }

    /**
     * Delete a terminator Delete a terminator by id. Requires admin access.
     *
     * @param id The id of the requested resource (required)
     * @param headers Optional headers to include in the request
     * @return CompletableFuture&lt;ApiResponse&lt;Empty&gt;&gt;
     * @throws ApiException if fails to make API call
     */
    public CompletableFuture<ApiResponse<Empty>> deleteTerminatorWithHttpInfo(
            @javax.annotation.Nonnull String id, Map<String, String> headers) throws ApiException {
        try {
            HttpRequest.Builder localVarRequestBuilder =
                    deleteTerminatorRequestBuilder(id, headers);
            return memberVarHttpClient
                    .sendAsync(
                            localVarRequestBuilder.build(),
                            HttpResponse.BodyHandlers.ofInputStream())
                    .thenComposeAsync(
                            localVarResponse -> {
                                if (memberVarAsyncResponseInterceptor != null) {
                                    memberVarAsyncResponseInterceptor.accept(localVarResponse);
                                }
                                if (localVarResponse.statusCode() / 100 != 2) {
                                    return CompletableFuture.failedFuture(
                                            getApiException("deleteTerminator", localVarResponse));
                                }
                                try {
                                    InputStream localVarResponseBody =
                                            ApiClient.getResponseBody(localVarResponse);
                                    try {
                                        if (localVarResponseBody == null) {
                                            return CompletableFuture.completedFuture(
                                                    new ApiResponse<Empty>(
                                                            localVarResponse.statusCode(),
                                                            localVarResponse.headers().map(),
                                                            null));
                                        }

                                        String responseBody =
                                                new String(localVarResponseBody.readAllBytes());
                                        Empty responseValue =
                                                responseBody.isBlank()
                                                        ? null
                                                        : memberVarObjectMapper.readValue(
                                                                responseBody,
                                                                new TypeReference<Empty>() {});

                                        return CompletableFuture.completedFuture(
                                                new ApiResponse<Empty>(
                                                        localVarResponse.statusCode(),
                                                        localVarResponse.headers().map(),
                                                        responseValue));
                                    } finally {
                                        if (localVarResponseBody != null) {
                                            localVarResponseBody.close();
                                        }
                                    }
                                } catch (IOException e) {
                                    return CompletableFuture.failedFuture(new ApiException(e));
                                }
                            });
        } catch (ApiException e) {
            return CompletableFuture.failedFuture(e);
        }
    }

    private HttpRequest.Builder deleteTerminatorRequestBuilder(
            @javax.annotation.Nonnull String id, Map<String, String> headers) throws ApiException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException(
                    400, "Missing the required parameter 'id' when calling deleteTerminator");
        }

        HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

        String localVarPath =
                "/terminators/{id}".replace("{id}", ApiClient.urlEncode(id.toString()));

        localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

        localVarRequestBuilder.header("Accept", "application/json");

        localVarRequestBuilder.method("DELETE", HttpRequest.BodyPublishers.noBody());
        if (memberVarReadTimeout != null) {
            localVarRequestBuilder.timeout(memberVarReadTimeout);
        }
        // Add custom headers if provided
        localVarRequestBuilder =
                HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
        if (memberVarInterceptor != null) {
            memberVarInterceptor.accept(localVarRequestBuilder);
        }
        return localVarRequestBuilder;
    }

    /**
     * Retrieves a single terminator Retrieves a single terminator by id. Requires admin access.
     *
     * @param id The id of the requested resource (required)
     * @return CompletableFuture&lt;DetailTerminatorEnvelope&gt;
     * @throws ApiException if fails to make API call
     */
    public CompletableFuture<DetailTerminatorEnvelope> detailTerminator(
            @javax.annotation.Nonnull String id) throws ApiException {
        return detailTerminator(id, null);
    }

    /**
     * Retrieves a single terminator Retrieves a single terminator by id. Requires admin access.
     *
     * @param id The id of the requested resource (required)
     * @param headers Optional headers to include in the request
     * @return CompletableFuture&lt;DetailTerminatorEnvelope&gt;
     * @throws ApiException if fails to make API call
     */
    public CompletableFuture<DetailTerminatorEnvelope> detailTerminator(
            @javax.annotation.Nonnull String id, Map<String, String> headers) throws ApiException {
        try {
            return detailTerminatorWithHttpInfo(id, headers).thenApply(ApiResponse::getData);
        } catch (ApiException e) {
            return CompletableFuture.failedFuture(e);
        }
    }

    /**
     * Retrieves a single terminator Retrieves a single terminator by id. Requires admin access.
     *
     * @param id The id of the requested resource (required)
     * @return CompletableFuture&lt;ApiResponse&lt;DetailTerminatorEnvelope&gt;&gt;
     * @throws ApiException if fails to make API call
     */
    public CompletableFuture<ApiResponse<DetailTerminatorEnvelope>> detailTerminatorWithHttpInfo(
            @javax.annotation.Nonnull String id) throws ApiException {
        return detailTerminatorWithHttpInfo(id, null);
    }

    /**
     * Retrieves a single terminator Retrieves a single terminator by id. Requires admin access.
     *
     * @param id The id of the requested resource (required)
     * @param headers Optional headers to include in the request
     * @return CompletableFuture&lt;ApiResponse&lt;DetailTerminatorEnvelope&gt;&gt;
     * @throws ApiException if fails to make API call
     */
    public CompletableFuture<ApiResponse<DetailTerminatorEnvelope>> detailTerminatorWithHttpInfo(
            @javax.annotation.Nonnull String id, Map<String, String> headers) throws ApiException {
        try {
            HttpRequest.Builder localVarRequestBuilder =
                    detailTerminatorRequestBuilder(id, headers);
            return memberVarHttpClient
                    .sendAsync(
                            localVarRequestBuilder.build(),
                            HttpResponse.BodyHandlers.ofInputStream())
                    .thenComposeAsync(
                            localVarResponse -> {
                                if (memberVarAsyncResponseInterceptor != null) {
                                    memberVarAsyncResponseInterceptor.accept(localVarResponse);
                                }
                                if (localVarResponse.statusCode() / 100 != 2) {
                                    return CompletableFuture.failedFuture(
                                            getApiException("detailTerminator", localVarResponse));
                                }
                                try {
                                    InputStream localVarResponseBody =
                                            ApiClient.getResponseBody(localVarResponse);
                                    try {
                                        if (localVarResponseBody == null) {
                                            return CompletableFuture.completedFuture(
                                                    new ApiResponse<DetailTerminatorEnvelope>(
                                                            localVarResponse.statusCode(),
                                                            localVarResponse.headers().map(),
                                                            null));
                                        }

                                        String responseBody =
                                                new String(localVarResponseBody.readAllBytes());
                                        DetailTerminatorEnvelope responseValue =
                                                responseBody.isBlank()
                                                        ? null
                                                        : memberVarObjectMapper.readValue(
                                                                responseBody,
                                                                new TypeReference<
                                                                        DetailTerminatorEnvelope>() {});

                                        return CompletableFuture.completedFuture(
                                                new ApiResponse<DetailTerminatorEnvelope>(
                                                        localVarResponse.statusCode(),
                                                        localVarResponse.headers().map(),
                                                        responseValue));
                                    } finally {
                                        if (localVarResponseBody != null) {
                                            localVarResponseBody.close();
                                        }
                                    }
                                } catch (IOException e) {
                                    return CompletableFuture.failedFuture(new ApiException(e));
                                }
                            });
        } catch (ApiException e) {
            return CompletableFuture.failedFuture(e);
        }
    }

    private HttpRequest.Builder detailTerminatorRequestBuilder(
            @javax.annotation.Nonnull String id, Map<String, String> headers) throws ApiException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException(
                    400, "Missing the required parameter 'id' when calling detailTerminator");
        }

        HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

        String localVarPath =
                "/terminators/{id}".replace("{id}", ApiClient.urlEncode(id.toString()));

        localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

        localVarRequestBuilder.header("Accept", "application/json");

        localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
        if (memberVarReadTimeout != null) {
            localVarRequestBuilder.timeout(memberVarReadTimeout);
        }
        // Add custom headers if provided
        localVarRequestBuilder =
                HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
        if (memberVarInterceptor != null) {
            memberVarInterceptor.accept(localVarRequestBuilder);
        }
        return localVarRequestBuilder;
    }

    /**
     * List terminators Retrieves a list of terminator resources; supports filtering, sorting, and
     * pagination. Requires admin access.
     *
     * @param limit (optional)
     * @param offset (optional)
     * @param filter (optional)
     * @return CompletableFuture&lt;ListTerminatorsEnvelope&gt;
     * @throws ApiException if fails to make API call
     */
    public CompletableFuture<ListTerminatorsEnvelope> listTerminators(
            @javax.annotation.Nullable Integer limit,
            @javax.annotation.Nullable Integer offset,
            @javax.annotation.Nullable String filter)
            throws ApiException {
        return listTerminators(limit, offset, filter, null);
    }

    /**
     * List terminators Retrieves a list of terminator resources; supports filtering, sorting, and
     * pagination. Requires admin access.
     *
     * @param limit (optional)
     * @param offset (optional)
     * @param filter (optional)
     * @param headers Optional headers to include in the request
     * @return CompletableFuture&lt;ListTerminatorsEnvelope&gt;
     * @throws ApiException if fails to make API call
     */
    public CompletableFuture<ListTerminatorsEnvelope> listTerminators(
            @javax.annotation.Nullable Integer limit,
            @javax.annotation.Nullable Integer offset,
            @javax.annotation.Nullable String filter,
            Map<String, String> headers)
            throws ApiException {
        try {
            return listTerminatorsWithHttpInfo(limit, offset, filter, headers)
                    .thenApply(ApiResponse::getData);
        } catch (ApiException e) {
            return CompletableFuture.failedFuture(e);
        }
    }

    /**
     * List terminators Retrieves a list of terminator resources; supports filtering, sorting, and
     * pagination. Requires admin access.
     *
     * @param limit (optional)
     * @param offset (optional)
     * @param filter (optional)
     * @return CompletableFuture&lt;ApiResponse&lt;ListTerminatorsEnvelope&gt;&gt;
     * @throws ApiException if fails to make API call
     */
    public CompletableFuture<ApiResponse<ListTerminatorsEnvelope>> listTerminatorsWithHttpInfo(
            @javax.annotation.Nullable Integer limit,
            @javax.annotation.Nullable Integer offset,
            @javax.annotation.Nullable String filter)
            throws ApiException {
        return listTerminatorsWithHttpInfo(limit, offset, filter, null);
    }

    /**
     * List terminators Retrieves a list of terminator resources; supports filtering, sorting, and
     * pagination. Requires admin access.
     *
     * @param limit (optional)
     * @param offset (optional)
     * @param filter (optional)
     * @param headers Optional headers to include in the request
     * @return CompletableFuture&lt;ApiResponse&lt;ListTerminatorsEnvelope&gt;&gt;
     * @throws ApiException if fails to make API call
     */
    public CompletableFuture<ApiResponse<ListTerminatorsEnvelope>> listTerminatorsWithHttpInfo(
            @javax.annotation.Nullable Integer limit,
            @javax.annotation.Nullable Integer offset,
            @javax.annotation.Nullable String filter,
            Map<String, String> headers)
            throws ApiException {
        try {
            HttpRequest.Builder localVarRequestBuilder =
                    listTerminatorsRequestBuilder(limit, offset, filter, headers);
            return memberVarHttpClient
                    .sendAsync(
                            localVarRequestBuilder.build(),
                            HttpResponse.BodyHandlers.ofInputStream())
                    .thenComposeAsync(
                            localVarResponse -> {
                                if (memberVarAsyncResponseInterceptor != null) {
                                    memberVarAsyncResponseInterceptor.accept(localVarResponse);
                                }
                                if (localVarResponse.statusCode() / 100 != 2) {
                                    return CompletableFuture.failedFuture(
                                            getApiException("listTerminators", localVarResponse));
                                }
                                try {
                                    InputStream localVarResponseBody =
                                            ApiClient.getResponseBody(localVarResponse);
                                    try {
                                        if (localVarResponseBody == null) {
                                            return CompletableFuture.completedFuture(
                                                    new ApiResponse<ListTerminatorsEnvelope>(
                                                            localVarResponse.statusCode(),
                                                            localVarResponse.headers().map(),
                                                            null));
                                        }

                                        String responseBody =
                                                new String(localVarResponseBody.readAllBytes());
                                        ListTerminatorsEnvelope responseValue =
                                                responseBody.isBlank()
                                                        ? null
                                                        : memberVarObjectMapper.readValue(
                                                                responseBody,
                                                                new TypeReference<
                                                                        ListTerminatorsEnvelope>() {});

                                        return CompletableFuture.completedFuture(
                                                new ApiResponse<ListTerminatorsEnvelope>(
                                                        localVarResponse.statusCode(),
                                                        localVarResponse.headers().map(),
                                                        responseValue));
                                    } finally {
                                        if (localVarResponseBody != null) {
                                            localVarResponseBody.close();
                                        }
                                    }
                                } catch (IOException e) {
                                    return CompletableFuture.failedFuture(new ApiException(e));
                                }
                            });
        } catch (ApiException e) {
            return CompletableFuture.failedFuture(e);
        }
    }

    private HttpRequest.Builder listTerminatorsRequestBuilder(
            @javax.annotation.Nullable Integer limit,
            @javax.annotation.Nullable Integer offset,
            @javax.annotation.Nullable String filter,
            Map<String, String> headers)
            throws ApiException {

        HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

        String localVarPath = "/terminators";

        List<Pair> localVarQueryParams = new ArrayList<>();
        StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
        String localVarQueryParameterBaseName;
        localVarQueryParameterBaseName = "limit";
        localVarQueryParams.addAll(ApiClient.parameterToPairs("limit", limit));
        localVarQueryParameterBaseName = "offset";
        localVarQueryParams.addAll(ApiClient.parameterToPairs("offset", offset));
        localVarQueryParameterBaseName = "filter";
        localVarQueryParams.addAll(ApiClient.parameterToPairs("filter", filter));

        if (!localVarQueryParams.isEmpty() || localVarQueryStringJoiner.length() != 0) {
            StringJoiner queryJoiner = new StringJoiner("&");
            localVarQueryParams.forEach(p -> queryJoiner.add(p.getName() + '=' + p.getValue()));
            if (localVarQueryStringJoiner.length() != 0) {
                queryJoiner.add(localVarQueryStringJoiner.toString());
            }
            localVarRequestBuilder.uri(
                    URI.create(memberVarBaseUri + localVarPath + '?' + queryJoiner.toString()));
        } else {
            localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));
        }

        localVarRequestBuilder.header("Accept", "application/json");

        localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
        if (memberVarReadTimeout != null) {
            localVarRequestBuilder.timeout(memberVarReadTimeout);
        }
        // Add custom headers if provided
        localVarRequestBuilder =
                HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
        if (memberVarInterceptor != null) {
            memberVarInterceptor.accept(localVarRequestBuilder);
        }
        return localVarRequestBuilder;
    }

    /**
     * Update the supplied fields on a terminator Update the supplied fields on a terminator.
     * Requires admin access.
     *
     * @param id The id of the requested resource (required)
     * @param terminator A terminator patch object (required)
     * @return CompletableFuture&lt;Empty&gt;
     * @throws ApiException if fails to make API call
     */
    public CompletableFuture<Empty> patchTerminator(
            @javax.annotation.Nonnull String id,
            @javax.annotation.Nonnull TerminatorPatch terminator)
            throws ApiException {
        return patchTerminator(id, terminator, null);
    }

    /**
     * Update the supplied fields on a terminator Update the supplied fields on a terminator.
     * Requires admin access.
     *
     * @param id The id of the requested resource (required)
     * @param terminator A terminator patch object (required)
     * @param headers Optional headers to include in the request
     * @return CompletableFuture&lt;Empty&gt;
     * @throws ApiException if fails to make API call
     */
    public CompletableFuture<Empty> patchTerminator(
            @javax.annotation.Nonnull String id,
            @javax.annotation.Nonnull TerminatorPatch terminator,
            Map<String, String> headers)
            throws ApiException {
        try {
            return patchTerminatorWithHttpInfo(id, terminator, headers)
                    .thenApply(ApiResponse::getData);
        } catch (ApiException e) {
            return CompletableFuture.failedFuture(e);
        }
    }

    /**
     * Update the supplied fields on a terminator Update the supplied fields on a terminator.
     * Requires admin access.
     *
     * @param id The id of the requested resource (required)
     * @param terminator A terminator patch object (required)
     * @return CompletableFuture&lt;ApiResponse&lt;Empty&gt;&gt;
     * @throws ApiException if fails to make API call
     */
    public CompletableFuture<ApiResponse<Empty>> patchTerminatorWithHttpInfo(
            @javax.annotation.Nonnull String id,
            @javax.annotation.Nonnull TerminatorPatch terminator)
            throws ApiException {
        return patchTerminatorWithHttpInfo(id, terminator, null);
    }

    /**
     * Update the supplied fields on a terminator Update the supplied fields on a terminator.
     * Requires admin access.
     *
     * @param id The id of the requested resource (required)
     * @param terminator A terminator patch object (required)
     * @param headers Optional headers to include in the request
     * @return CompletableFuture&lt;ApiResponse&lt;Empty&gt;&gt;
     * @throws ApiException if fails to make API call
     */
    public CompletableFuture<ApiResponse<Empty>> patchTerminatorWithHttpInfo(
            @javax.annotation.Nonnull String id,
            @javax.annotation.Nonnull TerminatorPatch terminator,
            Map<String, String> headers)
            throws ApiException {
        try {
            HttpRequest.Builder localVarRequestBuilder =
                    patchTerminatorRequestBuilder(id, terminator, headers);
            return memberVarHttpClient
                    .sendAsync(
                            localVarRequestBuilder.build(),
                            HttpResponse.BodyHandlers.ofInputStream())
                    .thenComposeAsync(
                            localVarResponse -> {
                                if (memberVarAsyncResponseInterceptor != null) {
                                    memberVarAsyncResponseInterceptor.accept(localVarResponse);
                                }
                                if (localVarResponse.statusCode() / 100 != 2) {
                                    return CompletableFuture.failedFuture(
                                            getApiException("patchTerminator", localVarResponse));
                                }
                                try {
                                    InputStream localVarResponseBody =
                                            ApiClient.getResponseBody(localVarResponse);
                                    try {
                                        if (localVarResponseBody == null) {
                                            return CompletableFuture.completedFuture(
                                                    new ApiResponse<Empty>(
                                                            localVarResponse.statusCode(),
                                                            localVarResponse.headers().map(),
                                                            null));
                                        }

                                        String responseBody =
                                                new String(localVarResponseBody.readAllBytes());
                                        Empty responseValue =
                                                responseBody.isBlank()
                                                        ? null
                                                        : memberVarObjectMapper.readValue(
                                                                responseBody,
                                                                new TypeReference<Empty>() {});

                                        return CompletableFuture.completedFuture(
                                                new ApiResponse<Empty>(
                                                        localVarResponse.statusCode(),
                                                        localVarResponse.headers().map(),
                                                        responseValue));
                                    } finally {
                                        if (localVarResponseBody != null) {
                                            localVarResponseBody.close();
                                        }
                                    }
                                } catch (IOException e) {
                                    return CompletableFuture.failedFuture(new ApiException(e));
                                }
                            });
        } catch (ApiException e) {
            return CompletableFuture.failedFuture(e);
        }
    }

    private HttpRequest.Builder patchTerminatorRequestBuilder(
            @javax.annotation.Nonnull String id,
            @javax.annotation.Nonnull TerminatorPatch terminator,
            Map<String, String> headers)
            throws ApiException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException(
                    400, "Missing the required parameter 'id' when calling patchTerminator");
        }
        // verify the required parameter 'terminator' is set
        if (terminator == null) {
            throw new ApiException(
                    400,
                    "Missing the required parameter 'terminator' when calling patchTerminator");
        }

        HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

        String localVarPath =
                "/terminators/{id}".replace("{id}", ApiClient.urlEncode(id.toString()));

        localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

        localVarRequestBuilder.header("Content-Type", "application/json");
        localVarRequestBuilder.header("Accept", "application/json");

        try {
            byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(terminator);
            localVarRequestBuilder.method(
                    "PATCH", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
        } catch (IOException e) {
            throw new ApiException(e);
        }
        if (memberVarReadTimeout != null) {
            localVarRequestBuilder.timeout(memberVarReadTimeout);
        }
        // Add custom headers if provided
        localVarRequestBuilder =
                HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
        if (memberVarInterceptor != null) {
            memberVarInterceptor.accept(localVarRequestBuilder);
        }
        return localVarRequestBuilder;
    }

    /**
     * Update all fields on a terminator Update all fields on a terminator by id. Requires admin
     * access.
     *
     * @param id The id of the requested resource (required)
     * @param terminator A terminator update object (required)
     * @return CompletableFuture&lt;Empty&gt;
     * @throws ApiException if fails to make API call
     */
    public CompletableFuture<Empty> updateTerminator(
            @javax.annotation.Nonnull String id,
            @javax.annotation.Nonnull TerminatorUpdate terminator)
            throws ApiException {
        return updateTerminator(id, terminator, null);
    }

    /**
     * Update all fields on a terminator Update all fields on a terminator by id. Requires admin
     * access.
     *
     * @param id The id of the requested resource (required)
     * @param terminator A terminator update object (required)
     * @param headers Optional headers to include in the request
     * @return CompletableFuture&lt;Empty&gt;
     * @throws ApiException if fails to make API call
     */
    public CompletableFuture<Empty> updateTerminator(
            @javax.annotation.Nonnull String id,
            @javax.annotation.Nonnull TerminatorUpdate terminator,
            Map<String, String> headers)
            throws ApiException {
        try {
            return updateTerminatorWithHttpInfo(id, terminator, headers)
                    .thenApply(ApiResponse::getData);
        } catch (ApiException e) {
            return CompletableFuture.failedFuture(e);
        }
    }

    /**
     * Update all fields on a terminator Update all fields on a terminator by id. Requires admin
     * access.
     *
     * @param id The id of the requested resource (required)
     * @param terminator A terminator update object (required)
     * @return CompletableFuture&lt;ApiResponse&lt;Empty&gt;&gt;
     * @throws ApiException if fails to make API call
     */
    public CompletableFuture<ApiResponse<Empty>> updateTerminatorWithHttpInfo(
            @javax.annotation.Nonnull String id,
            @javax.annotation.Nonnull TerminatorUpdate terminator)
            throws ApiException {
        return updateTerminatorWithHttpInfo(id, terminator, null);
    }

    /**
     * Update all fields on a terminator Update all fields on a terminator by id. Requires admin
     * access.
     *
     * @param id The id of the requested resource (required)
     * @param terminator A terminator update object (required)
     * @param headers Optional headers to include in the request
     * @return CompletableFuture&lt;ApiResponse&lt;Empty&gt;&gt;
     * @throws ApiException if fails to make API call
     */
    public CompletableFuture<ApiResponse<Empty>> updateTerminatorWithHttpInfo(
            @javax.annotation.Nonnull String id,
            @javax.annotation.Nonnull TerminatorUpdate terminator,
            Map<String, String> headers)
            throws ApiException {
        try {
            HttpRequest.Builder localVarRequestBuilder =
                    updateTerminatorRequestBuilder(id, terminator, headers);
            return memberVarHttpClient
                    .sendAsync(
                            localVarRequestBuilder.build(),
                            HttpResponse.BodyHandlers.ofInputStream())
                    .thenComposeAsync(
                            localVarResponse -> {
                                if (memberVarAsyncResponseInterceptor != null) {
                                    memberVarAsyncResponseInterceptor.accept(localVarResponse);
                                }
                                if (localVarResponse.statusCode() / 100 != 2) {
                                    return CompletableFuture.failedFuture(
                                            getApiException("updateTerminator", localVarResponse));
                                }
                                try {
                                    InputStream localVarResponseBody =
                                            ApiClient.getResponseBody(localVarResponse);
                                    try {
                                        if (localVarResponseBody == null) {
                                            return CompletableFuture.completedFuture(
                                                    new ApiResponse<Empty>(
                                                            localVarResponse.statusCode(),
                                                            localVarResponse.headers().map(),
                                                            null));
                                        }

                                        String responseBody =
                                                new String(localVarResponseBody.readAllBytes());
                                        Empty responseValue =
                                                responseBody.isBlank()
                                                        ? null
                                                        : memberVarObjectMapper.readValue(
                                                                responseBody,
                                                                new TypeReference<Empty>() {});

                                        return CompletableFuture.completedFuture(
                                                new ApiResponse<Empty>(
                                                        localVarResponse.statusCode(),
                                                        localVarResponse.headers().map(),
                                                        responseValue));
                                    } finally {
                                        if (localVarResponseBody != null) {
                                            localVarResponseBody.close();
                                        }
                                    }
                                } catch (IOException e) {
                                    return CompletableFuture.failedFuture(new ApiException(e));
                                }
                            });
        } catch (ApiException e) {
            return CompletableFuture.failedFuture(e);
        }
    }

    private HttpRequest.Builder updateTerminatorRequestBuilder(
            @javax.annotation.Nonnull String id,
            @javax.annotation.Nonnull TerminatorUpdate terminator,
            Map<String, String> headers)
            throws ApiException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException(
                    400, "Missing the required parameter 'id' when calling updateTerminator");
        }
        // verify the required parameter 'terminator' is set
        if (terminator == null) {
            throw new ApiException(
                    400,
                    "Missing the required parameter 'terminator' when calling updateTerminator");
        }

        HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

        String localVarPath =
                "/terminators/{id}".replace("{id}", ApiClient.urlEncode(id.toString()));

        localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

        localVarRequestBuilder.header("Content-Type", "application/json");
        localVarRequestBuilder.header("Accept", "application/json");

        try {
            byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(terminator);
            localVarRequestBuilder.method(
                    "PUT", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
        } catch (IOException e) {
            throw new ApiException(e);
        }
        if (memberVarReadTimeout != null) {
            localVarRequestBuilder.timeout(memberVarReadTimeout);
        }
        // Add custom headers if provided
        localVarRequestBuilder =
                HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
        if (memberVarInterceptor != null) {
            memberVarInterceptor.accept(localVarRequestBuilder);
        }
        return localVarRequestBuilder;
    }
}
